name: deploy

on: 
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
    FUNCTIONAPP_NAME: BicepFunctionApp
  
jobs:
  build-and-deploy-code:
    runs-on: windows-latest
    needs: deploy
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@master
    - name: Setup DotNet 3.1 Environment
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'

    - name: 'Resolve Project Dependencies Using Dotnet'
      shell: pwsh
      run: |
        dotnet build --configuration Release --output ./output
    - uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}  
    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: ${{ env.FUNCTIONAPP_NAME }}
        package: 'output'
        
        
     